exports.jobs = [
    {
      "id": 1,
      "title": "Développeur JavaScript",
      "company": "AT Sure",
      "email": "sm2@test.fr",
      "city": "Rennes",
      "zipcode": 35000,
      "description": "Arrogance Technology est une société à taille humaine, leader sur le marché, nous cherchons un développeur Front connaissant TOUS les frameworks y compris ceux qui ne sont pas encore sortis. Si vous parlez Anglais, Allemand et Espagnol et avez des notions de Mandarin, c'est un plus.",
      "contract": "CDI",
      "salary": 25000,
      "currency": "eu",
      "startdate": "ASAP",
      "experience": "junior",
      "status": "cadre",
      "area": "pas de déplacement",
      "field": "aéronautique",
      "publishdate": "2019-06-12",
      "lastupdate": "2019-07-05"
    },
    {
      "id": 2,
      "title": "Développeur Fullstack",
      "company": "c-noo-les-meilleurs",
      "email": "sm2@test.fr",
      "city": "St Malo",
      "zipcode": 35400,
      "description": "Vous maitrisez Angular, Node et MongoDB : ne cherchez plus, c'est nous les vrais leaders sur le marché. Vous souhaitez intégrer une société qui saura vous faire grandir techniquement et humainement, ne cherchez plus (bis) : ça n'existe pas ! (attends t'es sûr qu'on peut le dire). Pour info, nous ne cherchons pas vraiment, c'est juste pour donner l'impression à nos concurrents que nous sommes en très forte croissance.",
      "contract": "CDI",
      "salary": 45000,
      "currency": "eu",
      "startdate": "ASAP",
      "experience": "senior",
      "status": "employé",
      "area": "national",
      "field": "édition",
      "publishdate": "2019-04-06",
      "lastupdate": "2019-04-06"
    },
    {
      "id": 3,
      "title": "Développeur Angular",
      "company": "SHT",
      "email": "sm2@test.fr",
      "city": "Nantes",
      "zipcode": 44000,
      "description": "Steak Haché Technologie cherche son expert pas cher : chez nous, le minimum c'est déjà trop. Alors envoie ton CV et tes prétentions, mais surtout le CV.",
      "contract": "CDI",
      "salary": 0,
      "currency": "eu",
      "startdate": "ASAP",
      "experience": "junior",
      "status": "stagiaire",
      "area": "europe",
      "field": "secteur d'avenir",
      "publishdate": "2019-07-05",
      "lastupdate": "2019-07-20"
    },
    {
      "id": 4,
      "title": "Développeur Angular",
      "company": "Palindrome",
      "email": "sm3@test.fr",
      "city": "Laval",
      "zipcode": 53000,
      "description": "'Engage le jeu que je le gagne' : c'est ce que tu pourras déclarer si tu maîtrises React, Redux et Node. Si en plus tu sais réparer un 'radar nu' et que tu habites sur 'un roc cornu', le poste est fait pour toi. On a déménagé à Laval pour aller au bout de notre obsession. Pas de babyfoot chez nous : on fait ... du Kayak :)",
      "contract": "CDI",
      "salary": 0,
      "currency": "eu",
      "startdate": "2019-09-20",
      "experience": "senior",
      "status": "cadre",
      "area": "Ouest",
      "field": "le monde du livre",
      "publishdate": "2019-07-01",
      "lastupdate": "2019-07-19"
    }
  ]